cid.js
index.js
package.json
test/test-errors.js
test/test-legacy.js
test/test-multicodec.js

mainly for testing purposes but also for stringification, make it disappear because it’s not uniquely mapped to the CID properties.
this PR builds on #6, hence the extra fluff that’s not in cid.js

hide CID#_baseCache so deepEquals() checks don’t look at it

---

cid.js
test/test-cid.js

Found that my entirely different CIDs were still passing `deepEqual()`! Properties need to be enumerable. This is chai using a `for ... in`: https://github.com/chaijs/deep-eql/blob/fa5c6042e5c127df12e1f3ee4b9f9b3e2302864c/index.js#L374-L380, Node.js `assert` relies on `Object.keys()`.

fix: make cid properties enumerable for deep-eql compat

---

bases/_base64-browser.js
bases/_base64.js
bases/base16.js
bases/base58.js
bases/base64.js
bytes.js
cid.js
codecs/raw.js
hashes/sha2-browser.js
index.js
legacy.js
package.json
test/test-bytes.js
test/test-cid.js
test/test-errors.js
test/test-legacy.js
test/test-multibase.js
test/test-multicodec.js
test/test-multihash.js

I’ve been hacking on the branch @vmx had originally created. It took more than I thought to get it all working nicely.
The tests passing in Node.js, still have some work to do in order to get the browser tests passing and to get the coverage back up to 100% now that the legacy interface has more code.

feat: Remove Buffer dependency, use Uint8Array

---

cid.js
test/test-cid.js

This was undone in e079ffe5 but the test still passed, so make the test more robust

fix: hide CID#_baseCache so deepEquals() checks don't see it (again)

---

index.js
test/test-multibase.js

https://github.com/ipld/js-dag-cbor/pull/1
same issue
I have mixed feelings about this, the backing buffer is there so we don't have to allocate these tiny buffers, and comparison going that deep is _probably_ wrong. In this case, whatever base-x is doing, it's allocating a _massive_ backing buffer that comes along for the ride.

fix: clean backing buffer from multibase decode

---

bases/_base64.js
bases/base58.js
bases/base64.js
basics.js
cid.js
index.js
legacy.js
package.json
polendina.webpack.config.cjs
rollup.config.js
test/test-bytes.js
test/test-cid.js
test/test-errors.js
test/test-legacy.js
test/test-multibase.js
test/test-multicodec.js
test/test-multihash.js

First of all: the `pkg.exports` spec defines that object key order is
being used when resolving for the targeted environment, see
https://github.com/uuidjs/uuid/pull/462#issuecomment-637571626
In order for `webpack@5` to pick up the `browser` overrides they must
come _before_ `import` and `require`, see
https://gist.github.com/sokra/e032a0f17c1721c71cfced6f14516c62 for
preliminary documentation.
To make full use of `pkg.exports` in node as well we can use package
self reference instead of local paths, see the discussion in
https://github.com/jkrems/proposal-pkg-exports/issues/47
Unfortunately the browser testing tool polendina doesn't play nice with
self reference since it only looks for bare module specifiers in
`node_modules` and `node_modules/polendina/node_modules`, see …

fix: leverage pkg.exports

---

cid.js

This came up in a conversation I had with @gozala
This feature is nice for a few reasons.
1) it’s a relatively unique property you can check that doesn’t rely on symbols.
2) this makes the toJSON() representation serializable through a Worker but, since it includes a circular reference, can still be understood as a CID instead of just a regular object.
3) this breaks CID serialization and causes an exception when you try to naively encode them as objects.
However, if we take this change it will require some updates to our codecs. In both `dag-cbor` and in `dag-json` we do an `isCircular` check before encoding an object and that runs through a relatively naive third party library that will now throw. But it’s already in my mental backlog to get rid of `is-circular` so it’s probably fine.

feat: asCID property self reference

---

cid.js
package.json
test/test-cid.js

This change builds upon #18 as per discussion at https://github.com/multiformats/js-cid/issues/111.
It does following:
- Introduces `.asCID` property that points to the CID instance that has it. This is a unique (enough) marker to distinguish CID values form other values.
- Unlike `[Symbol.for('@ipld/js-cid/CID')]` marker this:
- Marker is preserved when CID is moved across JS realms / threads (so CIDs could be identified on receiver end without sender having to do any work).
- Introduces `CID.asCID` static method as a replacement for `CID.isCID`, which improves following:
- Two incompatible versions of CID library could co-exist and inter-op (as long as binary interface doesn't change)
- Code (codecs) which migrate to `CID.asCID` will be able to work with `CID` instances from other …

Implement CID.asCID and depracte CID.isCID

---

README.md

I didn’t realize that CIDv0 is only supported for SHA2-256 multihash so it’s actually not that difficult to detect, we just can’t
ever use 18 as a CID version number :)

feat: create CIDv0 from multihash buffer

---

bytes.js
cid.js
index.js
legacy.js
test/test-cid.js
test/test-legacy.js

This pull request changes CID representation to a glorified ArrayBuffer view (as per https://github.com/multiformats/js-cid/issues/111#issuecomment-656281072 and discussions in other higher bandwidth channels). Primary goal here is to illustrate and discuss the concept, which is why it end up mixing bunch of things (we can spin smaller pull request from this as necessary).
- Mail goal is to make CID just be a glorified view over the binary CID (just like all the other typed arrays). That is to say it complies with `ArrayBufferView` interface as defined below:
```js
interface ArrayBufferView {
byteOffset: number,
byteLength: number,
buffer: ArrayBuffer
}
```
- This also implies that `CID` can represent view into the larger buffer. This provides nice benefits when using binary protocol to …

Array buffer view

---

.eslintrc
.github/workflows/mikeals-workflow.yml
.github/workflows/typecheck.yml
package.json
src/bases/base.js
src/bases/base32.js
src/bases/base58.js
src/bases/base64-browser.js
src/block.js
src/bytes.js
src/cid.js
src/hashes/digest.js
src/hashes/hasher.js
src/hashes/sha2-browser.js
src/index.js
src/legacy.js
src/varint.js
test/test-block.js
tsconfig.json
vendor/base-x.d.ts
vendor/varint.d.ts

- Makes some changes to make it type check
- Adds type check action on pull requests and reports missmatches inline (screenshots from #44)
- Adds typedef generation to a build script

feat: type checking & type generation

---

package.json
test/ts-use/package.json

We publish from the `dist` directory, to package.json needs to have a `"typesVersions"` relative to that and currently it points into `dist/` so the types don't get picked up by consuming packages.
This fixes that problem and the local checks run so it seems that this is fine for local dev 🤞.
ts-use was also calling to `npx tsc` which is the wrong package (needs to be `-p typescript`).

fix: run ts-use check properly

---

README.md

prompted by #50, we've had this out for a few weeks now

docs: add dag-pb to multicodecs list

---

README.md

See discussion in #48: there's a bug in the TypeScript compiler which is causing the type definitions for this project to generate errors. @Gozala suggested that a note in the README would be welcome.

Add note to README with TypeScript workaround for #48

---

package.json

Signed-off-by: Carson Farmer <carson.farmer@gmail.com>
Some parsers don't understand exports, and fallback to main... right now, this causes issues, as the "main" key points to a non-existent file. For example, in React Native, the following error occurs when importing this module:
```
Error: While trying to resolve module `multiformats` from file `.../MyApp/node_modules/some/dep/package/index.js`, the package `.../MyApp/node_modules/multiformats/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`.../MyApp/node_modules/multiformats/index`. Indeed, none of these files exist:
```
The "fix" is to manually go in and specify:
```
...
"main": "./cjs/src/index.js",
...
```

fix: specify src path to index.js

---

LICENSE-APACHE
LICENSE-MIT
README.md

Was looking for something quick to add so we can get https://github.com/multiformats/js-multiformats/issues/55 sorted out now that we have a new ipjs with https://github.com/mikeal/ipjs/pull/4 published so we can get docs included in the npm package. We're missing the usual legals, the only notice in here is in the package.json currently.

doc: add missing legal notices

---

src/cid.js
test/fixtures/invalid-multihash.js
test/test-cid.js

There's two commits in here, the first one could go against `master` but it's used for the second one which is intended for `crypto`, #349. If this is an acceptable approach I'll write up some additional tests to exercise `encodedLength()` a bit more (CIDv0 and bad bytes - and these would be good to do with the aes tests too).
Ref: https://github.com/ipld/specs/pull/349#issuecomment-759649987

add CID.encodedLength() & remove leading uint32 CID length from encoded aes form

---

src/legacy.js
test/test-legacy.js

The resolving always returns a `remainderPath`, even if it's an empty string.

fix: fix legacy resolving

---

package.json
src/hashes/sha2-browser.js

`window` isn't available in web workers, hence use `self` instead.
@Gozala you know a thing or to about web workers. Is that the correct fix that also works outside of web workers?

fix: make hashing work in web workers

---

src/cid.js

Enables us to constrain CID version to `0 | 1`, similar to how we used to do with the `cids` module.

feat!: add CIDVersion type

---

src/cid.js
test/test-cid.js

`base56btc` should be `base58btc`

fix: typo in error name

---

src/bases/interface.ts
src/cid.js
src/hashes/interface.ts

This appears to have been missed off, unless it's been done on purpose?
Makes `MultihashHasher` consistent with `MultibaseEncoder`, `BlockEncoder`, etc.
Also fixes a small typo.

feat: add name and code fields to MultihashHasher interface

---

src/bases/base16.js
src/bases/base32.js

These were not present, I'm not sure why not but we use them in a few places so add them so we don't need to change the case of strings before decoding them.

feat: add missing upper case versions of base16 and base32 multibase codecs

---

package.json
src/bases/base.js
src/bases/base32.js
src/bases/base36.js
src/bases/base58.js
test/test-multibase.js

Adds base36 encoding/decoding as it's in the multibase table and is used by ipns.
Reuses the base-x alphabet implementation as that's what js-multibase used to do.
Moves the `implement` function from base58.js into base.js so it can be reused by base36.

feat: add base36 encoding/decoding

---

package.json
src/bases/base.js
src/bases/base10.js
src/bases/base2.js
src/bases/base32.js
src/bases/base36.js
src/bases/base58.js
src/bases/base8.js
src/bases/identity.js
src/basics.js
test/fixtures/test-throw.js
test/test-cid.js
test/test-multibase-spec.js
test/test-multibase.js
test/test-multicodec.js
vendor/base-x.d.ts
vendor/base-x.js

1. ports spec tests from js-multibase
2. adds missing identity/base2/8/10 base encodings
3. Standardises error messages - before you might get `'invalid base32upper character'` or `'Non-base32 character'` depending on if rfc4648 or base-x was used (also notice the base name change in the error message), now you always get `'Non-base32upper character'`

feat: add missing encodings and spec tests

---

package.json
src/codecs/json.js
src/codecs/raw.js

(and update deps)
FIxes https://github.com/multiformats/js-multiformats/issues/116 I believe
types/codecs/json.d.ts is now:
```ts
export const name: "json";
export const code: 512;
export function encode<T>(node: T): ByteView<T>;
export function decode<T>(data: ByteView<T>): T;
export type ByteView<T> = import('./interface').ByteView<T>;
//# sourceMappingURL=json.d.ts.map
```
(previous is https://unpkg.com/browse/multiformats@9.4.6/types/codecs/json.d.ts)
types/codecs/raw.d.ts is now:
```ts
/**
* @template T
* @typedef {import('./interface').ByteView<T>} ByteView
*/
export const name: "raw";
export const code: 85;
export function encode(node: Uint8Array): ByteView<Uint8Array>;
export function decode(data: ByteView<Uint8Array>): Uint8Array;
export type ByteView<T> = …
```

fix: adjust codec exports to make TS defn's more correct

---

README.md
package.json
src/traversal.js
test/test-traversal.js

This PR aims to fix #118.
A new file `traverse.js` with a function called `walk` inside it. `walk` is a utility function that allows a use to walk through the links in a block and, for each one, fetch that block using the load function, which is passed in to walk as a parameter.
The naming is chosen to align with `go-ipld-prime`.
Test cases have been written, which have led to two new dev dependencies being added in this PR: `@ipld/dag-pb` and `sinon`.

traverse walk function added with tests

---

src/traversal.js

this commit got lost in the wash of the #127 collaboration process, which has just been merged

fix: make 'seen' option for walk() optional

---

examples/block-interface.js
examples/cid-interface.js
examples/multicodec-interface.js
examples/multihash-interface.js
package.json

Extracted and updated 4 examples from README file:
- **cid-interface.js**: consolidates examples on basic CID creation, multibase interface
- **block-interface.js**: block interface example from README with add'l outputs and checks
- **multicodec-interface.js**: borrows README multicodec example, no changes
- **multihash-interface.js**: expands on multihash examples
Additionally, updated a dependency for '@ipld/dag-cbor' package which was throwing errors in **block-interface.js**

doc: extract runnable examples from README + update dependencies

---

src/traversal.js
tsconfig.json

I'm presuming this is a temporary fix in tsconfig.json, removing "tests" for
now to get back the old behaviour of just publishing src/ -> types/ rather
than having both src/ and tests/ both in types/ as subdirectories which
breaks types mappings.

fix(types): fix publishing of types

---

.github/workflows/typecheck.yml
package.json
test/tsconfig.json
tsconfig.json

This pull reverts https://github.com/multiformats/js-multiformats/commit/b0467e52870a91f3fc3122afb969505a31dc3210 which reports type errors in the diff view as opposed to just dumping it into output.
It also changes TS configuration as follows:
1. Moves tsconfig.json to the package root from src. That is more idiomatic and removes need for path mapping in tests, because TS now knows that linked multiformats package is project reference.
2. Updates .d.ts paths to include `src`. As it turns out `composite` flag in tsconfig causes dir stracture to be retained & that flag is necessary to enable project references. We do not however generate types for tests though because those aren't included.
3. Github action now points to test/tsconfig.json to type check everything. Because that …

Reanable tsc action and reconfigure project slightly

---

.gitignore
src/hashes/hasher.js
src/hashes/identity.js
src/hashes/interface.ts
test/test-multihash.js
test/tsconfig.json

feat: define sync multihash hasher interface

---

src/hashes/identity.js

basics.js uses `...identity` from the import, so as of 9.6.0 (via #160) `name` and friends get mixed up as hashers, which they are not.
This could be fixed in basics.js, but I think its usage tells us that #160 was a breaking change. So we'll do a revert-ish of the exports, and deal with the interface later with a breaking change if we think that a `*` export of identity (which wouldn't match the sha2 export) is the right way to go.
Fixes: https://github.com/ipfs/js-ipfs/issues/4020

fix: export only `identity` hasher const

---

src/hashes/identity.js

Fix API unintentional API change introduced by #160 which removed `encode` method.

fix: add encode to identity

---

src/cid.js

Motivation:
* 'code' isn't very helpful to a beginner because it has many possible definitions
Concerns:
* Am I even understanding this right?

update docs for CID `code` param to clarify "What kind of code?"

---

src/varint.js
test/test-varint.js

Adds optional `offset` parameter to `varint.decode` to allow decoding varints at arbitrary offsets without having to create intermediary `Uint8Array`s.
Whenever I have to deal with format that puts multiple varints e.g. `<code><size><bytes>` I find myself having to read first varint then to read second I'm forced to create another Uint8Array view. With this change it would be possible to just specify offset and avoid creating unnecessary objects.

feat: add optional offset param to varint.decode

---

test/test-cid.spec.js

This adds a test test that is expected to fail on #202 because getters on prototypes aren't going to be retained when moving things across JS realms. Use of getter on the instance or actual property does not has this problem.

chore: add test for structural copying

---

package.json
src/cid.js
test/test-cid.spec.js

`Object.defineProperties` is a performance bottleneck in applications that create lots and lots of CIDs (e.g. IPFS) so this PR removes it.
The `asCID` property is changed to be a [private class field](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) which requires increasing the minimum supported EcmaScript version but I don't know if that's a big deal or not.  It does seem to make the property non-enumerable though.
The CID class now implements a new `Link` interface that has public read-only `byteOffset` and `byteLength` properties so these become regular properties.  Similarly `code`, `version`, `multihash` and `bytes` become writable/configurable but they are also marked with `@readonly` so maybe that's enough?
Fixes #200

fix: remove use of Object.defineProperties in CID class

---

src/cid.js
test/test-cid.spec.js

Fixes #208 by converting `.byteOffset` and `.byteLength` properties to getters.
Supersedes #210

fix: convert byteOffset and byteLength to getters

---

test/test-varint.spec.js

Renames file so it's run along with all the other tests.
Before:
```console
447 passing (613ms)
1 pending
```
After:
```console
448 passing (621ms)
1 pending
```

chore: rename varint test file so it is run

---

package.json
test/test-block.spec.js
test/test-bytes.spec.js
test/test-cid.spec.js
test/test-link.spec.js
test/test-multibase-spec.spec.js
test/test-multibase.spec.js
test/test-multicodec.spec.js
test/test-multihash.spec.js
test/test-traversal.spec.js

Aegir has `chai` preconfigured with the relevant plugins so use that instead of declaring additional dependencies for slighter faster install times.

chore: remove unnecessary dev deps

---

src/cid.js
src/link.js
test/test-cid.spec.js

As per https://github.com/multiformats/js-multiformats/issues/212 making `asCID` enumerable breaks tests where modules don't handle self-referential data properly.
As proposed in https://github.com/multiformats/js-multiformats/issues/213 this swaps `cid.CID === cid` for `cid['/'] === cid.bytes` as a mechanism to tell consumers that the object in question is a `CID` which lets them write CBOR with the correct tags, for example.
Fixes #212
Closes #213

fix: use slash as flag that an object is a CID

---

.gitignore
README.md
package.json

Updates aegir to the latest version which has reinstated the `docs` command to publish typedocs in the `gh-pages` branch of repos.
A `typedoc-urls.json` file is now generated as part of the docs run which allows cross-linking between module docs.
This file lives at the "well known" location of `dist/typedoc-urls.json` in the published tarball, so the `files` list in `package.json` needed changing as it's currently only publishing `dist/types`.
See https://multiformats.github.io/js-multiaddr for an example.

docs: publish typedocs in gh-pages branch

---

package.json
src/block.js
test/test-block.spec.js

If a block _**is a**_ CID, it is not listed by the block `.links()` method. This PR fixes that.
For example, this is a block that is a CID:
```console
$ echo '{ "/": "bafyreihlhgo2srya7ihdyc5ae76rki47irecf4thjfjhsmrjyeurlyhbua" }' | ipfs dag put
bafyreiexxrljy6el4v7phukkux3ukhzuiuajsilzd63576oysy3vhll3ia
```
P.S. I also removed the `npm run lint` command from the `test` script since the `no-only-tests` rule was in the way of me being able to test my work. It is run in CI already. I can revert if anyone feels strongly in the opposite direction.
---
As an aside:
It looks like there's not really a way to _path_ through these kind of blocks, at least not with go/js ipfs.
For example, here's a tree with `node => CID node => node`:
```console
$ echo '{ "bar": "Hello World!" }' | ipfs dag put …
```

fix: list links of a block that _is a_ CID

---

package.json

Enable shipping a minified browser bundle.
Fixes #234

fix: build browser bundle

---

src/block/interface.ts
src/cid.js
src/hashes/digest.js

Fixes typos in comments used for generated documentation

docs: fix typos in jsdoc comments

---

src/cid.js
src/link.js
src/link/interface.ts
test/test-cid.spec.js
test/test-link.spec.js

Changes toJSON implementation of the CID so it returns [Link in DAG-JSON format](https://ipld.io/specs/codecs/dag-json/spec/#links) as opposed to object with Uint8Array which gets munged with `JSON.stringify`
Fixes #228

feat!: Make link.toJSON return a DAG-JSON link

---

src/cid.js
test/test-cid.spec.js

Add a check to CID.parse to throw on a CID v0 string with explict multibase, e.g. `zQmPr755CxWUwt39C2Yiw4UGKrv16uZhSgeZJmoHUUS9TSJ`
>  the multibase of the string representation is always base58btc and implicit (not written)
– https://github.com/multiformats/cid#versions
We're seeing pinning service requests comming in from the wild with the undesriable multibase prefix, and the expectation was that CID.parse would have thrown and spared us from having to deal with them.
Fixes: https://github.com/multiformats/js-multiformats/issues/240 
See also: https://github.com/ipfs/kubo/issues/9556
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>

fix: throw on CID.parse v0 string with multibase prefix

---

package.json

Interfaces from the interface files in this module are [imported](https://github.com/ipld/js-dag-cbor/blob/master/src/index.js#L9) in other modules, so they need to be in the exports map otherwise tsc can fail to build dependant modules.

fix: add interface files to the exports map

---

package.json
src/hashes/sha1-browser.js
src/hashes/sha1.js
test/test-multihash.spec.js

It's old and insecure but it's used in the wild so we need to be able to handle it.

feat: add sha1 support

---

package.json

The types and import fields were pointing to the wrong files so correct them.

fix: update link interface path in exports map

---

src/block/interface.ts
src/codecs/interface.ts
src/codecs/json.ts
src/codecs/raw.ts
test/test-multicodec.spec.ts

When using `fetch` to download something over HTTP, it only makes an `ArrayBuffer` available, not a `Uint8Array`.
`TextDecoder` supports decoding `ArrayBuffer`s, and the `raw` codec already turns passed `ArrayBuffer`s into `Uint8Array`s so this is just a type change.
Instead of:
```js
const res = await fetch('...')
const obj = json.decode(new Uint8Array(await res.arrayBuffer()))
```
we can do:
```js
const res = await fetch('...')
const obj = json.decode(await res.arrayBuffer())
```

feat: support decoding ArrayBuffers

---

src/codecs/interface.ts

Adds support for generic types to the `encode` and `decode` methods on
the `BlockCodec` interface.
I don't believe this to be a breaking change as the generic type is inferred by the
typescript compiler and will only be a narrowing of the `Universe` generic type on `BlockCodec`, previously named `T`.
Related: https://github.com/multiformats/js-multiformats/issues/293

feat: BlockCodec methods are generic

---

src/codecs/interface.ts

Reverts multiformats/js-multiformats#294
Ref: #300 
@tabcat

fix: revert "feat: BlockCodec methods are generic"

---

src/cid.ts
test/test-cid.spec.ts

This PR aims to support base36 out of the box, without having to specify base explicitly.
Rationale is that base36 is used across ecosystem for PeerIDs that have to be represented in base36 to fit in a single DNS label (due to limit of 63 characters).

fix: CID.parse(base36)

---

src/hashes/digest.ts
src/hashes/identity.ts
test/test-multihash.spec.ts

To give a hint to tsc that a `MultihashDigest` has a specific code, add a disambiguator `hasCode` function.
This lets us define functions that require a certain multihash code with type saftey.

feat: add hasCode to Digest

---

src/bases/base.ts

Making a performance improvement here to rfc4648 base decoding (e.g. base64, base32, base16).  On each decoding call we were building-up a dictionary mapping alphabet characters to their index—now this dictionary is built ahead of time.
Benching `CID.parse()` against 100,000 base32 CIDs sees an improvement of about 33-35% with this change (node v22.15.1 / macOS / ARM).

fix: perf improvement for rfc4648 base decoding
